### ISSUE TITLE
Select a software license

### ISSUE THREAD

**Issue by davidwesst** [lean-alchemy/shootout#10]
Decide on what software license we will use moving towards v1.0 (IE -> Initial Release). This should be selected in context with what people can do with an open source project. Discussion to occur in the comments.

Resource: http://choosealicense.com/

Outcome should be the commit of a LICENSE.md file to the root of the repository.

**Comment by Chrinkus** [comment]
It seems this comes down to how we want other people to contribute to our project. Who or what are we intending to protect here?

**Comment by davidwesst** [comment]
Here's the only thing I can think of:
- As we develop the game, we'll be exposing our source code to everyone. If we don't get the game into a marketplace then others could do it.
- That being said, even when we do a release into a marketplace, others could clone it and push it out themselves.

**Comment by Chrinkus** [comment]
Okay good. All this time I've been wondering about whether I was a dick for wanting to protect our project.
Lock it down, yo.

**Comment by davidwesst** [comment]
License-wise, we have few options then especially if we want to protect it commercially. We can look on making the code private for now by moving it to BitBucket or we can use the ["No License"](http://choosealicense.com/licenses/no-license/) option.

Thoughts?

**Comment by davidwesst** [comment]
Another idea: One of us could buy some private repositories ($5/month) and host a private repository that we can share.

[Bitbucket](https://bitbucket.org/) is still a good and free private option. Setup an account and take a look.

**Comment by Chrinkus** [comment]
I'll check it out. What are a few other repo options that cost money. Is there one you like?

**Comment by davidwesst** [comment]
Github is the biggest player that focuses on providing features for source code and git repo management. Cheapest paid option, but you're basically only buying privacy.

Bitbucket is a light weight version of many the [Atlassian](https://www.atlassian.com/) products, which I've used in industry before. Again, really good tool, but the paid option gets pricey really quickly.

Another one would be [Visual Studio Online](https://www.visualstudio.com/en-us/products/what-is-visual-studio-online-vs.aspx) as it supports Git and is REALLY full featured, like almost too much (Online code editor, repositories, build engine, issue tracker, testing suite...) but you only need to use what you want and you pay for the extra services you want. For example, if we wanted to run a load test, we'd pay for the load test computer time and such.

Private repositories and issue tracking are definitely free. Personally, I'd be really interested in using that one considering I'm a Microsoft person. Free for the first 5 users on your project. Plus, it has Microsoft's backing and they really like NodeJS and have been moving in that direction for the past year. Even converting some of their core developer tools to use Node.

**Comment by Chrinkus** [comment]
Can I use VSO on mac?

**Comment by davidwesst** [comment]
It's totally browser based, so yeah. Plus, I understand (never tested it) with Visual Studio Code which also works on all platforms.

**Comment by Chrinkus** [comment]
Ok. If we switch to VSO what is the process?

**Comment by davidwesst** [comment]
You'll need to create an account with VSO, then I'll create a team and add you to it. Then we push our repository to our team on VSO.

Only rework we'll have to do is remake our issues and milestones. No big deal. If you make an account this morning, I'll get something going for us this afternoon.

**Comment by Chrinkus** [comment]
I have to create an account URL for myself? Just myName.visualstudio.com?

**Comment by davidwesst** [comment]
Yup. Once you have that, share you username with me and I'll make a team project.

**Comment by davidwesst** [comment]
It appears that I misunderstood how VSO works with accounts VS organizations. So, I created leanalchemy.visualstudio.com and invited you to the team and made you an administrator.

Created issue #14 to capture the migration task, where we will add the LICENSE.md file to reference the [No License](http://choosealicense.com/licenses/no-license/) for the time being, where it will be registered to both of us.
